apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-search-demo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instant-search-demo
  template:
    metadata:
      labels:
        app: instant-search-demo
    spec:
      containers:
      - name: instant-search-demo
        image: instant-search-demo:dev
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2

